# Tomcat
server:
  port: 19004
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.126.43.197:31193/learned_asked_article?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=&serverTimezone=Asia/Shanghai
    username: root
    password: mysql_root_123@112..
  data:
    mongodb:
      host: 101.126.43.197
      port: 32407
      username: adminRoot
      password: mymongoroot_1234@
      database: article
      authentication-database: admin
#      uri: mongodb://adminRoot:mymongoroot_1234%40@101.126.43.197:32407/article


# MyBatis配置
mybatis-flex:
  type-aliases-package: com.vk.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:mapper/**/*Mapper.xml

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG