spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.126.43.197:31193/learned_asked_behaviour?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=&serverTimezone=Asia/Shanghai
    username: root
    password: mysql_root_123@112..


xxl:
  job:
    admin:
      accessToken: default_token
      addresses: http://101.126.43.197:30243/xxl-job-admin/
    executor:
      appname: job-executor-behaviour-01
      logpath: /vk/prod/xxl-job
      logretentiondays: 15
