server:
  port: 16001
spring:
  cloud:
    gateway:
      # 网关全局跨域配置
#      globalcors:
#        add-to-simple-url-handler-mapping: true
#        cors-configurations:
#          '[/**]': # 匹配所有请求
#            allowedOrigins: "*" #跨域处理 允许所有的域
#            allowedHeaders: "*"
#            allowedMethods: # 支持的方法
#              - GET
#              - POST
#              - PUT
#              - DELETE
#              - OPTIONS
#            maxAge: 18000
#            allowCredentials: true
      routes:
        # 用户微服
        - id: vk-service-system
          uri: lb://vk-service-system
          predicates:
            - Path=/dev-api/system/**
          filters:
            - StripPrefix=2
#            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        # 权限微服
        - id: vk-service-auth
          uri: lb://vk-service-auth
          predicates:
            - Path=/dev-api/auth/**
          filters:
            - StripPrefix=2
        # 后台微服
        - id: vk-service-admin
          uri: lb://vk-service-admin
          predicates:
            - Path=/dev-api/admin/**
          filters:
            - StripPrefix=2
        # 频道与行为微服
        - id: vk-service-analyze
          uri: lb://vk-service-analyze
          predicates:
            - Path=/dev-api/analyze/**
          filters:
            - StripPrefix=2

