server:
  port: 16001
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: '*' #跨域处理 允许所有的域
            allowedHeaders: '*'
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        # 用户微服
        - id: service-admin
          uri: lb://service-admin
          predicates:
            - Path=/dev-api/admin/**
          filters:
            - StripPrefix=2
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/dev-api/user-a/**
          filters:
            - StripPrefix=2
