apiVersion: v1
kind: PersistentVolume
metadata:
  name: jk-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master
  hostPath:
    path: /mnt/data/jk
---
#Namespace dev
apiVersion: v1
kind: Namespace
metadata:
  name: jk
---
apiVersion: v1
kind: Service
metadata:
  name: jk-svc
  namespace: jk
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - port: 8080
      name: web
      nodePort: 31397
    - port: 50000
      name: agent
      nodePort: 31529
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins
  namespace: jk
spec:
  serviceName: "jenkins"
  replicas: 1  # 可以增加副本数来实现高可用
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      # 署 master 节点需要
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"  # 容忍控制平面节点的 taint
      containers:
        - name: jenkins
          image: jenkins/jenkins:jdk21
          env:
            - name: TZ
              value: "Asia/Shanghai"  # 设置时区为上海
          ports:
            - containerPort: 8080
            - containerPort: 50000
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: jenkins-home
            - mountPath: /certs/client  # 挂载 /certs/client
              name: jenkins-certs  # 挂载的 volume 名称
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
      volumes:
        - name: jenkins-certs
          hostPath:
            path: /usr/local/jenkins/certs
  volumeClaimTemplates:
    - metadata:
        name: jenkins-home
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
---
