---

apiVersion: v1
kind: Namespace
metadata:
  name: jk
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-sa
  namespace: jk
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
  - nonResourceURLs: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-role-binding
subjects:
  - kind: ServiceAccount
    name: jenkins-sa
    namespace: jk
roleRef:
  kind: ClusterRole
  name: jenkins-role  # 使用自定义的 jenkins-role，而不是 cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: jk-svc
  namespace: jk
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - port: 8080
      name: web
      nodePort: 31397
    - port: 50000
      name: agent
      nodePort: 31529
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins
  namespace: jk
spec:
  serviceName: "jenkins"
  replicas: 1  # 可以增加副本数来实现高可用
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-sa
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - master
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"  # 容忍控制平面节点的 taint
      containers:
        - name: jenkins
          image: jenkins/jenkins:jdk21
          env:
            - name: TZ
              value: "Asia/Shanghai"  # 设置时区为上海
          ports:
            - containerPort: 8080
            - containerPort: 50000
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -c
                  - |
                    tar -xzvf /var/jenkins_home/tools/nerdctl-2.0.3-linux-amd64.tar.gz -C /usr/local/bin/
          securityContext:
            runAsUser: 0  # 运行容器时使用 root 用户
            runAsGroup: 0 # 运行容器时使用 root 用户组
            allowPrivilegeEscalation: true  # 允许特权提升，给容器更多权限
          volumeMounts:
            - mountPath: /usr/local/bin/kubectl  # 容器内的路径
              name: kubectl-volume
            - mountPath: /usr/local/bin/buildctl
              name: buildctl-volume
            - mountPath: /var/run/buildkit/buildkitd.sock
              name: buildkitd-sock
            - mountPath: /var/run/containerd/containerd.sock
              name: containerd-sock
            - mountPath: /var/jenkins_home
              name: jenkins-home
            - mountPath: /certs/client  # 挂载 /certs/client
              name: jenkins-certs  # 挂载的 volume 名称
      volumes:
        - name: kubectl-volume
          hostPath:
            path: /usr/bin/kubectl
        - name: buildctl-volume
          hostPath:
            path: /usr/local/bin/buildctl
        - name: buildkitd-sock
          hostPath:
            path: /var/run/buildkit/buildkitd.sock
            type: Socket
        - name: containerd-sock
          hostPath:
            path: /var/run/containerd/containerd.sock
            type: Socket
        - name: jenkins-certs
          hostPath:
            path: /mnt/data/jk/certs
        - name: jenkins-home
          hostPath:
            path: /mnt/data/jk
---
