apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: dev
spec:
  capacity:
    storage: 10Gi  # 定义存储大小
  volumeMode: Filesystem  # 默认为文件系统
  accessModes:
    - ReadWriteMany  # 多节点可读写
  persistentVolumeReclaimPolicy: Retain  # PV 被释放时保留数据
  nfs:
    path: /root/data/nfs
    server: 10.66.66.1
---