apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node2
  hostPath:
    path: /mnt/data/es
---
#Namespace dev
apiVersion: v1
kind: Namespace
metadata:
  name: es
---
#Service 暴露端口 3306
apiVersion: v1
kind: Service
metadata:
  name: es-svc
  namespace: es
  labels:
    app: es
spec:
  ports:
    - name: http
      port: 9200
      targetPort: 9200
    - name: transport
      port: 9300
      targetPort: 9300
  selector:
    app: es
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: es
spec:
  serviceName: "elasticsearch"  # 必须指定 Service 名称
  replicas: 1  # 副本数，根据需要调整
  selector:
    matchLabels:
      app: es
  template:
    metadata:
      labels:
        app: es
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:8.17.2  # 使用适合的版本
          env:
            - name: TZ
              value: "Asia/Shanghai"  # 设置时区为上海
            - name: discovery.type
              value: zen-disco
            - name: "ES_JAVA_OPTS"
              value: "-Xms512m -Xmx1g"
          ports:
            - containerPort: 9200
            - containerPort: 9300
          resources: #资源限制和请求的设置
            limits: #资源限制的设置
              cpu: "1"
              memory: "1Gi"
          livenessProbe: #对Pod内各容器健康检查的设置，当探测无响应几次后将自动重启该容器
            tcpSocket: #对Pod内个容器健康检查方式设置为tcpSocket方式
              port: 9200
            initialDelaySeconds: 10   #容器启动完成后首次探测的时间，单位为秒
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: es-storage
              mountPath: /usr/share/elasticsearch
            - name: host-time  #挂载本地时区
              mountPath: /etc/localtime
              readOnly: true
  volumeClaimTemplates:
    - metadata:
        name: es-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi  # 持久化存储大小
