---
#Namespace dev
apiVersion: v1
kind: Namespace
metadata:
  name: es
---
#Service 暴露端口 3306
apiVersion: v1
kind: Service
metadata:
  name: es-svc
  namespace: es
spec:
  ports:
    - name: http
      port: 9200
      nodePort: 32062
    - name: transport
      port: 9300
      nodePort: 31230
  selector:
    app: es
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es
  namespace: es
spec:
  serviceName: "es"  # 必须指定 Service 名称
  replicas: 1  # 副本数，根据需要调整
  selector:
    matchLabels:
      app: es
  template:
    metadata:
      labels:
        app: es
    spec:
      containers:
        - name: es
          image: elasticsearch:8.17.2  # 使用适合的版本
          env:
            - name: TZ
              value: "Asia/Shanghai"  # 设置时区为上海
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          ports:
            - containerPort: 9200
            - containerPort: 9300
          resources:
            limits:
              cpu: "0.5"
              memory: "1Gi"
          livenessProbe: #对Pod内各容器健康检查的设置，当探测无响应几次后将自动重启该容器
            tcpSocket: #对Pod内个容器健康检查方式设置为tcpSocket方式
              port: 9200
            initialDelaySeconds: 30   #容器启动完成后首次探测的时间，单位为秒
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: data
            - mountPath: /usr/share/elasticsearch/plugins
              name: plugins
            - mountPath: /usr/share/elasticsearch/logs
              name: logs
            - name: timezone
              mountPath: /etc/localtime
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - hostPath:
            path: /es/esData/data
            type: DirectoryOrCreate
          name: data
        - hostPath:
            path: /es/esData/plugins
            type: DirectoryOrCreate
          name: plugins
        - hostPath:
            path: /es/esData/logs
            type: DirectoryOrCreate
          name: logs
