---

apiVersion: v1
kind: Namespace
metadata:
  name: es
---
#Service 暴露端口 3306
apiVersion: v1
kind: Service
metadata:
  name: es-svc
  namespace: es
spec:
  ports:
    - name: http
      port: 9200
      nodePort: 32062
    - name: transport
      port: 9300
      nodePort: 31230
  selector:
    app: es
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es
  namespace: es
spec:
  serviceName: "es"  # 必须指定 Service 名称
  replicas: 1  # 副本数，根据需要调整
  selector:
    matchLabels:
      app: es
  template:
    metadata:
      labels:
        app: es
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - node2
#      ik 分词 initContainers
      initContainers:
        - name: install-ik
          image: elasticsearch:8.17.2  # 使用适合的版本
          command:
            - sh
            - -c
            - |
              # 检查插件是否已安装，若未安装则执行安装
              if [ ! -f "/usr/share/elasticsearch/plugins/analysis-ik/plugin-descriptor.properties" ]; then
                ./bin/elasticsearch-plugin install -b https://get.infini.cloud/elasticsearch/analysis-ik/8.17.2
                # 修改插件目录权限，确保主容器可访问
                chown -R 1000:0 /usr/share/elasticsearch/plugins
              fi
          securityContext:
            runAsUser: 0  # 以root用户运行以确保权限
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/plugins
              name: plugins
      containers:
        - name: es
          image: elasticsearch:8.17.2  # 使用适合的版本
          env:
            - name: TZ
              value: "Asia/Shanghai"  # 设置时区为上海
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xms1g -Xmx1g"
            - name: ELASTIC_PASSWORD
              value: "E-M4C7g1d_CrrtFI9xFF"  # 设置 elastic 用户密码
            - name: KIBANA_SYSTEM_PASSWORD
              value: "LLB37kNRP8zpqe_4UERT"
          ports:
            - containerPort: 9200
            - containerPort: 9300
          resources:
            limits:
              cpu: "500m"
              memory: "2Gi"
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: data
            - mountPath: /usr/share/elasticsearch/plugins
              name: plugins
            - mountPath: /usr/share/elasticsearch/logs
              name: logs
      volumes:
        - hostPath:
            path: /mnt/data/esData/data
            type: DirectoryOrCreate
          name: data
        - hostPath:
            path: /mnt/data/esData/plugins
            type: DirectoryOrCreate
          name: plugins
        - hostPath:
            path: /mnt/data/esData/logs
            type: DirectoryOrCreate
          name: logs
