---
#Namespace dev
apiVersion: v1
kind: Namespace
metadata:
  name: kb
---
#Service 暴露端口 5601
apiVersion: v1
kind: Service
metadata:
  name: kb-svc
  namespace: kb
spec:
  ports:
    - port: 5601
      nodePort: 32214
  selector:
    app: kibana
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kibana
  namespace: kb
spec:
  serviceName: "kibana"
  replicas: 1  # 副本数，根据需要调整
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - node4
      containers:
        - name: kibana
          image: kibana:8.17.2  # 使用适合的版本
          env:
            - name: TZ
              value: "Asia/Shanghai"  # 设置时区为上海
            - name: ELASTICSEARCH_HOSTS
              value: '["http://es-svc.es.svc.cluster.local:9200"]'
            - name: ELASTICSEARCH_USERNAME
              value: 'kibana_system'
            - name: ELASTICSEARCH_PASSWORD
              value: 'esRootKibana'
            - name: i18n.locale
              value: 'zh-CN'
          ports:
            - containerPort: 5601
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"

