---
#Namespace dev
apiVersion: v1
kind: Namespace
metadata:
  name: nc
---
#Secret mysql密码
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
  namespace: nc
type: Opaque
data:
  password: bXlzcWxfcm9vdF8xMjNAMTEyLi4=  # Base64 编码后的密码
---
apiVersion: v1
kind: Service
metadata:
  name: nc-svc
  namespace: nc
spec:
  type: NodePort
  selector:
    app: nacos
  ports:
    - port: 8848
      nodePort: 31269
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos
  namespace: nc
spec:
  serviceName: "nacos"
  replicas: 1  # 可以增加副本数来实现高可用
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      labels:
        app: nacos
    spec:
      # 署 master 节点需要
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"  # 容忍控制平面节点的 taint
      containers:
        - name: nacos
          image: nacos/nacos-server:v2.5.0
          env:
            - name: TZ
              value: "Asia/Shanghai"  # 设置时区为上海
            - name: MYSQL_SERVICE_HOST
              value: "mysql-svc.mysql.svc.cluster.local:3306"
            - name: MYSQL_SERVICE_DB_NAME
              value: "nacos_config"
            - name: MYSQL_SERVICE_USER
              value: "root"
            - name: MYSQL_SERVICE_PASSWORD
              valueFrom: #环境变量的值
                secretKeyRef:
                  name: mysql-pass
                  key: password # root 用户密码
          ports:
            - containerPort: 8848
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
          volumeMounts:
            - name: timezone
              mountPath: /etc/localtime
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
---
