---
#Namespace dev
apiVersion: v1
kind: Namespace
metadata:
  name: nc
---
apiVersion: v1
kind: Service
metadata:
  name: nc-svc
  namespace: nc
spec:
  type: NodePort
  selector:
    app: nacos
  ports:
    - port: 8848
      nodePort: 31269
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos
  namespace: nc
spec:
  serviceName: "nacos"
  replicas: 1  # 可以增加副本数来实现高可用
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      labels:
        app: nacos
    spec:
      # 署 master 节点需要
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"  # 容忍控制平面节点的 taint
      containers:
        - name: nacos
          image: nacos/nacos-server:v2.5.0
          env:
            - name: MODE
              value: "standalone"  # 单机启动
            - name: TZ
              value: "Asia/Shanghai"  # 设置时区为上海
            - name: MYSQL_SERVICE_HOST
              value: "mysql-svc.mysql.svc.cluster.local"
            - name: MYSQL_SERVICE_DB_NAME
              value: "nacos_config"
            - name: MYSQL_SERVICE_USER
              value: "root"
            - name: MYSQL_SERVICE_PASSWORD
              value: "mysql_root_123@112.."
          ports:
            - containerPort: 8848
          livenessProbe: #对Pod内各容器健康检查的设置，当探测无响应几次后将自动重启该容器
            tcpSocket: #对Pod内个容器健康检查方式设置为tcpSocket方式
              port: 8848
            initialDelaySeconds: 10   #容器启动完成后首次探测的时间，单位为秒
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
          volumeMounts:
            - name: timezone
              mountPath: /etc/localtime
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
---
