apiVersion: v1
kind: PersistentVolume
metadata:
  name: xxl-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node3
  hostPath:
    path: /mnt/data/nc
---
#Namespace dev
apiVersion: v1
kind: Namespace
metadata:
  name: xxl
---
apiVersion: v1
kind: Service
metadata:
  name: xxl-svc
  namespace: xxl
spec:
  type: NodePort
  selector:
    app: xxl
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: xxl-job
  namespace: xxl
spec:
  serviceName: "xxl-job"
  replicas: 1
  selector:
    matchLabels:
      app: xxl-job
  template:
    metadata:
      labels:
        app: xxl-job
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: xxl-job
              topologyKey: kubernetes.io/hostname
      containers:
        - name: xxl-job
          image: xuxueli/xxl-job-admin:3.0.0
          ports:
            - containerPort: 8080
          env:
            - name: PARAMS
              value: "--spring.datasource.url=jdbc:mysql://127.0.0.1:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
            - name: TZ
              value: "Asia/Shanghai"  # 设置时区为上海
          volumeMounts:
            - name: xxl-data
              mountPath: /data/applogs
          resources: #资源限制和请求的设置
            limits: #资源限制的设置
              cpu: "1" #Cpu的限制，单位为core数，将用于docker run --cpu-shares参数
              memory: "512Mi"  #内存限制，单位可以为Mib/Gib，将用于docker run --memory参数
          livenessProbe: #对Pod内各容器健康检查的设置，当探测无响应几次后将自动重启该容器
            tcpSocket: #对Pod内个容器健康检查方式设置为tcpSocket方式
              port: 8080
            initialDelaySeconds: 30   #容器启动完成后首次探测的时间，单位为秒
            successThreshold: 1
            failureThreshold: 3
  volumeClaimTemplates:
    - metadata:
        name: xxl-data
      spec:
        storageClassName: standard
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi
---