server:
  port: 16003
spring:
  cloud:
    gateway:
      routes:
        # 用户行为
        - id: vk-service-behaviour
          uri: lb://vk-service-behaviour
          predicates:
            - Path=/dev-collection/behaviour/**
          filters:
            - StripPrefix=2
        #统计信息
        - id: vk-service-analyze
          uri: lb://vk-service-analyze
          predicates:
            - Path=/dev-collection/analyze/**
          filters:
            - StripPrefix=2
        #dfs
        - id: vk-service-dfs
          uri: lb://vk-service-dfs
          predicates:
            - Path=/dev-collection/dfs/**
          filters:
            - StripPrefix=2