server:
  port: 16002
spring:
  cloud:
    gateway:
      routes:
        # 评论
        - id: vk-service-comment
          uri: lb://vk-service-comment
          predicates:
            - Path=/dev-core/comment/**
          filters:
            - StripPrefix=2
        # 搜索
        - id: vk-service-search
          uri: lb://vk-service-search
          predicates:
            - Path=/dev-core/search/**
          filters:
            - StripPrefix=2
        # 文章
        - id: vk-service-article
          uri: lb://vk-service-article
          predicates:
            - Path=/dev-core/article/**
          filters:
            - StripPrefix=2